[package]
name = "devil_bot_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["codec"] }
futures = "*"
futures-util = "*"
tokio-tungstenite = { version = "*", features = ["native-tls", "rustls-tls-webpki-roots"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yml = "*"
reqwest = { version = "*", features = ["multipart", "stream", "json", "blocking", "serde_json"] }
rand = "*"
chrono = "*"
urlencoding = "*"
tor_client = "0.0.11"

void_log = { git = "https://gitee.com/orange_union/void_log.git" }
