[package]
name = "devil_bot_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"
tokio-tungstenite = { version = "0.24.0", features = ["rustls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yml = "0.0.12"
reqwest = { version = "0.12.8", features = ["multipart", "json", "stream", "rustls-tls"] }
rand = "0.8.5"
chrono = "0.4.38"
urlencoding = "2.1.3"
tor_client = "0.0.11"

void_log = { git = "https://gitee.com/orange_union/void_log.git" }
